main/urls.py
from django.urls import path

from main.views import *

app_name = "main"
urlpatterns = [
    path("", index, name="index"),
    path("view/<str:slug>", page, name="page"),
    path("actions/add-page", add_page, name="add_page"),
]

sharednotes/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include("main.urls")),
    path('user/', include("userapp.urls")),    
    path('admin/', admin.site.urls),
]

userapp/urls.py
from django.urls import path
from .views import *

app_name = "userapp"
urlpatterns = [
    path("login", login_view, name="login"),
    path("logout", logout_view, name="logout"),
    path("auth/<int:user_id>/<str:token>/", auth, name="auth"),

]

main/models.py
from slugify import slugify

from django.db.models.signals import pre_save
from django.db import models


class BaseModel(models.Model):
    added = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        abstract = True
        
class History(BaseModel):
    note = models.ForeignKey('Note', on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return "{}{}".format(str(self.note), self.added)
    
class Note(models.Model):
    title = models.CharField(max_length=100)
    slug = models.CharField(max_length=100, unique=True)
    text = models.TextField()

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

        
def save_history(sender, instance, update_fields=None, **kwargs):
    try:
        old_instance = Note.objects.get(id=instance.id)
    except Note.DoesNotExist:  # to handle initial object creation
        return None

    h = History(note=instance, text=instance.text)
    h.save()

pre_save.connect(save_history, sender=Note)

userapp/models.py
from django.db import models

main/forms.py
from django.forms import ModelForm

from .models import Note

class AddPageForm(ModelForm):
    class Meta:
        model = Note
        fields = ("title", )
        

main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Note, History
from .forms import AddPageForm


def index(request):
    user = request.user
    if user.is_authenticated:
        notes = Note.objects.filter()
    else:
        notes = []
    return render(request, "index.html", {"notes": notes})


def page(request, slug):
    note = get_object_404(Note, slug=slug)
    return render(request, "page.html", {"note": note})


def page_history(request, slug):
    note = get_object_404(Note, slug=slug)
    history_list = History.objects.filter(note=note).order_by("-added")
    return render(request, "page-history.html", {"history": history})


@login_required
def add_page(request):
    if request.method == "POST":
        form = AddPage(request.POST)
        if form.is_valid():
            inst = form.save()
            return HttpResponseRedirect(reverse("main:page", args=(inst.slug,)))

userapp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.cache import never_cache
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from django.template.loader import render_to_string
from django.core.mail import send_mail, mail_admins
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

from emailuser.models import manual_create_email_user
from emailuser.models import EmailUserForm

from djangohelpers.utils import gen_url


@never_cache
def login_view(request):
    sended = False
    if request.method == "POST":
        form = EmailUserForm(request.POST)
        if form.is_valid():  # All validation rules pass
            email = form.cleaned_data["email"]
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                user = User.objects.create_user(
                    email=form.cleaned_data["email"],
                    username=form.cleaned_data["email"],
                    password=gen_url(20),
                )
                user.save()

            try:
                token = user.emailuser.generate_token()
            except:
                manual_create_email_user(user)
                token = user.emailuser.generate_token()
            # try:
            if settings.DEBUG:
                print("Token - %s" % token)
            auth_link = reverse(
                "userapp:auth", kwargs={"user_id": user.pk, "token": token}
            )
            # tmp_token = gen_url(5)
            msg = render_to_string(
                "user/auth-email.html",
                {
                    "site_url": settings.SITE_URL,
                    "auth_link": auth_link,
                    "support_email": settings.SERVER_EMAIL,
                    # "token": token
                },
            )
            subj = "Вход на сайт: %s" % settings.SITE_NAME
            if settings.DEBUG:
                print(subj)
                print(msg)

            send_mail(
                subj,
                msg,
                u"%s" % settings.SERVER_EMAIL,
                [email],
                fail_silently=settings.DEBUG,
            )

            sended = True
        else:
            print(form.errors)

    else:
        form = InviteForm()
    return render(
        request,
        "user/login.html",
        {"form": form, "sended": sended, "support_email": settings.SUPPORT_EMAIL},
    )


@never_cache
def auth(request, user_id, token):
    get_user = get_object_or_404(User, pk=user_id)
    user = authenticate(email=get_user.email, token=token)
    if settings.DEBUG:
        print("User: %s" % user)
        print("Email:%s, Token: %s" % (get_user.email, token))
    if user is not None:
        if user.is_active:
            if settings.DEBUG:
                print("Logging in..")
            login(request, user)
    return render(request, "user/auth.html", {"user": user})




@login_required
def logout_view(request):
    logout(request)
    return redirect("/")

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Записи{% endblock %}</title>
        <meta charset="UTF-8">		
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{{ STATIC_URL }}css/bulma.min.css" />	
        <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" />
        <link href="{{ STATIC_URL }}img/favicon.png?v=1" rel='shortcut icon'/>
        <link href="{{ STATIC_URL }}css/all.min.css" rel="stylesheet"> <!--load all styles -->
        <script defer src="{{ STATIC_URL }}js/scripts.js?v=1.2" ></script>
        
    </head>
    <body class="b" >

        {% block nav %}
            {% if user.is_authenticated %}
                <nav class="navbar" role="navigation" aria-label="main navigation">
                    <div class="navbar-brand">
                        <a class="navbar-item" href="">
                            <img src="{{ STATIC_URL }}img/logo.png" alt="Notes" width="32">
                            Записи
                        </a>
                    </div>
                    <div class="navbar-end">
                        <div class="navbar-item">
                            <div class="buttons">
                                {% if profile %}
                                    <a class="button is-light" href="#">
                                        {{ profile }}
                                    </a>
                                {% endif %}
                                
                                <a class="button is-primary" href="{% url 'userapp:logout' %}" >
                                    <strong>Выход</strong>
                                </a>
                            </div>
                        </div>
                    </div>
                </nav>

            {% endif %}
        {% endblock %}

        {% block full %}
            <div class="container" id="main-container" >
                {% block content %}{% endblock %}
            </div>
        {% endblock %}
        
        <footer class="footer">
            {% block footer %}
                <div class="columns">
                    <div class="column">
                        <a href="#">Описание системы</a>
                    </div>
                    <div class="column">
                    </div>
                    <div class="column">
                    </div>
                </div>
        {% endblock %}
    </footer>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
    {% if user.is_authenticated %}
    <ul>
    {% for n in notes %}
        <li><a href="{% url 'main:page' slug=n.slug %}">{{ n }}</a></li>
    {% endfor %}
    </ul>
    <hr />
    Добавить страницу: <br />
    <form action="{% url 'main:add_page' %}" method="post" >{% csrf_token %}
        Название: <input type="text" placeholder="Тайтл новой страницы" name="title" />
    </form>
    {% else %}
    <a href="">Войти</a>
    {% endif %}
{% endblock %}

templates/user/auth-email.html
Вход на сайт {{ site_url }}
Для входа на сайт пройдите по ссылке: {{ site_url }}{{ auth_link }} 
Если у Вас возникли проблемы со входом напишите письмо на {{ support_email }}

templates/user/auth.html
{% extends "base.html" %}

{% block content %}

    <section class="hero is-fullheight">
        <div class="hero-body">
            <div class="container has-text-centered">
                {% if user.is_authenticated %}
                    <h3 class="title has-text-black">    
                        Добро пожаловать {{ user }}!
                    </h3>
                    Теперь вы можете <br />
                    <a href="{% url 'main:index' %}">перейти на главную страницу</a>.
                {% else %}
                    Ошибка входа, возможно ссылка устарела. <a href="{% url 'userapp:login' %}">Попробуйте еще раз</a>. Или обратитесь в поддержку.
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

templates/user/inform-email.html
Новое уведомление: {{ msg }}

templates/user/login.html
{% extends 'base.html' %}
{% block content %}
    <section class="hero is-fullheight">
        <div class="hero-body">
            <div class="container has-text-centered">
                {% if sended %}
                    <h3 class="title has-text-black">Ура!</h3>
                    На ваш адрес электронной почты выслано письмо для авторизации.
                    <br />
                    Просто пройдите по ссылке из письма для авторизации на сайте.<br />
                    У нас нет паролей, каждый раз для авторизации используется почта.<br />

                    p.s. Иногда письма попадают в спам - поэтому рекомендуем добавить нашу почту <b>{{ support_email }}</b> в список контактов.
                {% else %}
                    <div class="column is-4 is-offset-4">
                        <h3 class="title has-text-black">Вход / Регистрация</h3>
                        <p class="subtitle has-text-black">Для регистрации введите адрес электронной почты и ваш инвайт. <br />
                        <b><i>Если вы уже зарегистрированы, вводить инвайт не нужно.</i></b></p> 
                    <div class="box">
                        <figure class="avatar">
                            <img src="{{ STATIC_URL }}img/logo.png" width="70px;">
                        </figure>
                        <form action="{% url 'userapp:login' %}" method="post">
                            {% csrf_token %}
                            <div class="field">
                                <div class="control">
                                    <input class="input is-large" type="email" placeholder="Адрес электронной почты" autofocus="" name="email" value="{% if form.email.value %}{{ form.email.value }}{% endif %}" >
                                    {% if form.email.errors %}
                                        <span class="has-text-danger">{{ form.email.errors }}</span>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="field">
                                <div class="control">
                                    <input class="input is-large" type="text" placeholder="Инвайт" name="invite" value="{% if form.invite.value %}{{ form.invite.value }}{% endif %}" >
                                    {% if form.invite.errors %}
                                        <span class="has-text-danger">{{ form.invite.errors }}</span>
                                    {% endif %}
                                    
                                </div>
                            </div> 
                            <!--<div class="field">
                                 <label class="checkbox">
                                 <input type="checkbox">
                                 Запомнить меня
                                 </label>
                                 </div>-->
                            
                            <button class="button is-block is-info is-large is-fullwidth">Войти <i class="fa fa-sign-in" aria-hidden="true"></i></button>
                            <div class="field">
                                <div class="control">
                                    <br />
                                    Если к вашему аккаунту уже подключен телеграм бот, просто отправьте ему любое сообщение, и он пришлёт ссылку для авторизации:
                                    <a class="button is-block is-primary is-large is-fullwidth" href="tg://resolve?domain={{ auth_tg_bot }}" class="tgme_action_button">Войти через TG бота</a>
                                </div>
                            </div>
                        </form>
                    </div>
                    <p class="has-text-grey">
                        <a href="/">Главная страница</a> &nbsp;·&nbsp;
                    </p>
                </div>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

templates/user/profile.html
{% extends "base.html" %}

{% block content %}

{% endblock %}